---
- name: Configure Cognito Groups and Seed Data
  hosts: local
  gather_facts: false
  vars:
    region: eu-west-1
  tasks:
    - name: Ensure Admin user exists
      community.aws.cognito_user:
        state: present
        user_pool_name: "task-mgmt-dev"
        username: admin@amalitech.com
        attributes:
          email: admin@amalitech.com
        temporary_password: TempPass123!
        region: "{{ region }}"

    - name: Add admin to Admin group
      community.aws.cognito_user_group:
        state: present
        user_pool_name: "task-mgmt-dev"
        group_name: Admin
        username: admin@amalitech.com
        region: "{{ region }}"